version: "3"

services:
  redis:
    image: redis:3.2.12
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
      - "./redis/data:/data"
    container_name: redis3.2
    command: redis-server --requirepass zhoupassword


  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    container_name: mysql5.7


  gowebapp:
    image: registry.cn-hangzhou.aliyuncs.com/zgang/gowebapp:v0.1.0
    restart: always
    ports:
      - "80:8080"
    container_name: gowebapp