appName: webapp
appEnv: local
appUrl: https://www.hello.com

db:
  connection: mysql
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  name: go_test_s
  host: 127.0.0.1
  user: root
  password: a1112223
  port: 3306

contacts:
  - name: itest
    email: test@test.com
  - name: zhougang
    email: hello@hello.com