1、排行榜
  统计每日排行榜数据
  排行榜数据导出
  排行榜审核
  脚本自动发放奖励
2、积分分润
  分润比例设置
  统计每个订单分润数据
  分润数据导出
  分润脚本总开关
  分润审核
  分润自动发放脚本
  分润错误日志展示
3、架构调整（战区）
   新的架构页面替换掉旧的架构页面
   战区和项目关联、导入、导出
   战区负责人、事业负责人、项目负责人导入&导出
   战区展示、编辑、筛选等